# Generated by Django 3.2.16 on 2023-01-02 00:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
